CC = g++
CFLAGS = -O3 -Wall -Werror
DEPFLAGS = -MT $@ -MMD
SRCEXT = cc

RM = rm -rf

#####################################################################
#                                                                   #
#  Convention:                                                      #
#      main() function should be in $(SRCDIR)/main.$(SRCEXT)        #
#                                                                   #
#####################################################################

APPNAME = pdacleaner

#############################
#      App directories      #
#############################

SRCDIR = src
BUILDDIR = build
BINDIR = bin
TARGET = $(BINDIR)/$(APPNAME)

##############################
#      Test directories      #
##############################

TDIR = tests
TSRCDIR = $(TDIR)/src
TBUILDDIR = $(TDIR)/build
TTARGET = $(TDIR)/run

######################################
#      App sources/objects/deps      #
######################################

SOURCES = $(shell find $(SRCDIR) -type f -name "*.$(SRCEXT)")
OBJECTS = $(patsubst $(SRCDIR)/%,$(BUILDDIR)/%,$(SOURCES:.$(SRCEXT)=.o))
DEPS = $(patsubst $(SRCDIR)/%,$(BUILDDIR)/%,$(SOURCES:.$(SRCEXT)=.d))
MAINOBJ = $(BUILDDIR)/main.o

#######################################
#      Test sources/objects/deps      #
#######################################

TSOURCES = $(shell find $(TSRCDIR) -type f -name "*.$(SRCEXT)")
TOBJECTS = $(patsubst $(TSRCDIR)/%,$(TBUILDDIR)/%,$(TSOURCES:.$(SRCEXT)=.o))
TOBJECTS += $(filter-out $(MAINOBJ),$(OBJECTS))
TDEPS = $(patsubst $(TSRCDIR)/%,$(TBUILDDIR)/%,$(TSOURCES:.$(SRCEXT)=.d))

#########################
#      App lib/inc      #
#########################

LIB = 
INC =

##########################
#      Test lib/inc      #
##########################

TLIB = -lgtest -lgtest_main
TLIB += $(LIB)
TINC = $(INC)
TINC += -I $(SRCDIR)

#########################
#      App Targets      #
#########################

$(TARGET): $(OBJECTS)
	@mkdir -p $(@D)
	$(CC) $^ -o $(TARGET) $(LIB)

$(BUILDDIR)/%.o: $(SRCDIR)/%.$(SRCEXT)
	@mkdir -p $(@D)
	$(CC) $(DEPFLAGS) $(CFLAGS) $(INC) -c -o $@ $<

##########################
#      Test Targets      #
##########################

.PHONY: test

test: $(TOBJECTS)
	$(CC) $^ -o $(TTARGET) $(TLIB)

$(TBUILDDIR)/%.o: $(TSRCDIR)/%.$(SRCEXT)
	@mkdir -p $(@D)
	$(CC) $(DEPFLAGS) $(CFLAGS) $(TINC) -c -o $@ $<

##########################
#      Misc Targets      #
##########################

.PHONY: clean

clean:
	$(RM) $(BUILDDIR) $(BINDIR)
	$(RM) $(TBUILDDIR) $(TTARGET)

###################################
#      Autogenerated Targets      #
###################################

-include $(DEPS)

-include $(TDEPS)
